version: '3'
services:


    gunicorn:
        build: ./
        ports:
            - "8000:8000"
        volumes:
            - ./cybermillionaire:/cybermillionaire
        networks:
            - nginx_network
            - db_network
        depends_on:
            - db
        environment:
           OPENAI_API_KEY: "sk-svcacct-EDG_w-BQGpTfMLf7CHBA-1Uoj2vIoXQpJLMVSNxs7Rf16r_lnqaCf7-9TV-tH8hZogKT3BlbkFJUKsX6XSGAr6s1Pw-wljTYF97wUjx_uA_ycdA-t0jUqMze5UtwdAhUuGVy0yZPV-ZjwAA"


    nginx:
        build: ./nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./cybermillionaire/static:/static
        depends_on:
            - gunicorn
        networks:
            - nginx_network
            
      
    db:
        build: ./mysql
        ports:
            - "3306:3306"
        volumes:
            - ./cybermillionaire:/cybermillionaire
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: Millionaire
        networks:
            - db_network
        
   
networks:
    nginx_network:
        driver: bridge
    db_network:
        driver: bridge






