version: '3'
services:


    gunicorn:
        build: ./
        ports:
            - "8000:8000"
        volumes:
            - ./cybermillionaire/static:/static
            - ./cybermillionaire:/cybermillionaire
        
      
    nginx:
        build: ./nginx
        ports:
            - 8800:80
        volumes:
            - ./cybermillionaire/static:/static
        depends_on:
            - gunicorn
            
   







