FROM httpd:2.4

# Chances are we can add the whole pull call (so the thing with the /mad/directories/ nd shit) with a COPY statement
# RUN apk update 
# RUN apk add vim
# RUN apk add curl
# RUN curl -fsSL https://get.docker.com | sh
# RUN sudo systemctl start docker
# RUN sudo usermod -aG docker $(whoami)

