name: Deploy with Docker

on:
  push:
    branches:
      - Django-branch  # Trigger on pull_requests to Django-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v3

    - name: Create .env file with secret
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
      # This will write the secret to the .env file, which you can use in your local environment.

    - name: Add .env to .gitignore
      run: |
        echo ".env" >> .gitignore
      # Adds .env to .gitignore to ensure it's not committed.

   # - name: Verify .env is ignored
   #   run: git status
   #   # Verify that the .env file is indeed ignored by Git.
